variable:
    dir: /home/imeoer/PROJECT/ink.go/src
    ink: ${dir}/ink
    blog: /home/imeoer/PROJECT/blog
    theme: ${blog}/theme
task:
    default:
        - ${build_theme}
        - ${build_ink}
    build_theme:
        - gulp --cwd ${theme}
    build_ink:
        - "cd ${dir}/ink && go build"
        - "${dir}/ink/ink preview ${blog} " # build.go path parse issue
    release:
        - $GOPATH/bin/goxc -d=${ink}/release -bc="linux windows"

watch:
    ${ink}/*.go: ${build_ink}
    ${ink}/source/*.md: ${build_ink}
    ${theme}/css/*.less: ${default}
    ${theme}/js/*.coffee: ${default}
    ${theme}/*.html: ${default}
