variable:
    blog: /home/imeoer/PROJECT/blog
    theme: ${blog}/theme
task:
    default:
        - ${build_theme}
        - ${build_ink}
    build_theme:
        - gulp --cwd ${theme}
    build_ink:
        - "go build"
        - "./ink preview ${blog}"
    release:
        - $GOPATH/bin/goxc -d=./release -bc="linux windows darwin"

watch:
    ./*.go: ${build_ink}
    ${theme}/less/*.less: ${default}
    ${theme}/coffee/*.coffee: ${default}
    ${theme}/*.html: ${default}
